
SELECT
 	T1.ID as customer_id,  
 	T1.FULLNAME,  
  	T1.BIODATA_ID,  
 	T1.DOB,  
 	T1.AGE,  
 	T1.GENDER,  
 	T1.BLOOD_GROUP_ID,  
 	T1.CODE,  
 	T1.RHESUS_TYPE,  
 	T1.HEIGHT,  
 	T1.WEIGHT,  
 	T1.CUSTOMER_RELATION_ID,  
 	T1.RELATION,  
 	T1.CHAT_COUNT,  
 	COUNT(A.CUSTOMER_ID) AS APPOINTMENT_COUNT  
 FROM T_APPOINTMENT A  
 RIGHT JOIN  
 
 	(SELECT B.ID AS BIODATA_ID,  
 			B.FULLNAME AS FULLNAME,  
 			C.ID AS ID,  
 	 		C.DOB AS DOB,  
 			CASE  
 				WHEN DATE_PART('YEAR', AGE(NOW(), C.DOB)) > 0 THEN CAST(DATE_PART('YEAR', AGE(NOW(), C.DOB)) AS TEXT) || ' ' || 'Tahun'  
 				ELSE CAST(DATE_PART('MONTH', AGE(NOW(), C.DOB)) AS TEXT) || ' ' || 'Bulan'  
 			END AS AGE,  
 	 		C.GENDER,  
 			C.BLOOD_GROUP_ID,  
 	 		BG.CODE,  
 			C.RHESUS_TYPE,  
 			C.HEIGHT,  
 			C.WEIGHT,  
 	 		CM.CUSTOMER_RELATION_ID,  
 			CR.NAME AS RELATION,  
 			COUNT(CC.CUSTOMER_ID) AS CHAT_COUNT,  
 	 		B.IS_DELETE  
 		FROM M_BIODATA B  
 		inner JOIN M_CUSTOMER C ON B.ID = C.BIODATA_ID  
 	 	left JOIN M_BLOOD_GROUP BG ON BG.ID = C.BLOOD_GROUP_ID  
 		inner JOIN M_CUSTOMER_MEMBER CM ON C.ID = CM.CUSTOMER_ID  
 		INNER JOIN M_CUSTOMER_RELATION CR ON CR.ID = CM.CUSTOMER_RELATION_ID  
 		LEFT JOIN T_CUSTOMER_CHAT CC ON C.ID = CC.CUSTOMER_ID  
 		WHERE CM.PARENT_BIODATA_ID = 1  
 		GROUP BY B.ID,  
 			B.FULLNAME,  
 			C.ID,  
 	 		C.DOB,  
 	 		C.GENDER,  
 			C.BLOOD_GROUP_ID,  
 		 	BG.CODE,  
 			C.RHESUS_TYPE,  
 			C.HEIGHT,  
 			C.WEIGHT,  
 	 		CM.CUSTOMER_RELATION_ID,  
 			CR.NAME,	  
 			B.IS_DELETE) T1 ON T1.ID = A.CUSTOMER_ID  
 WHERE fullname ilike '%%' AND T1.IS_DELETE = FALSE  
 GROUP BY T1.BIODATA_ID,  
 	T1.FULLNAME,  
 	T1.ID,  
 	T1.DOB,  
 	T1.AGE,  
 	T1.GENDER,  
 	T1.BLOOD_GROUP_ID,  
 	T1.CODE,  
 	T1.RHESUS_TYPE,  
 	T1.HEIGHT,  
 	T1.WEIGHT,  
 	T1.CUSTOMER_RELATION_ID,  
 	T1.RELATION,  
 	T1.CHAT_COUNT
