version: '1.0'
services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=POS310
  app:
    container_name: pos310
    image: pos310
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/POS310
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    build:
      context: .
    ports:
      - 80:80
    depends_on:
      - db